### ISSUE TITLE
获取缓存大小和清空缓存？

### ISSUE THREAD

**Issue by jueduibishi** [marujun/DataManager#1]
另外可以缓存post请求嘛？

**Comment by marujun** [comment]
可以缓存post请求的；
缓存的图片文件目录：[UIImage cacheDirectory]
获取缓存图片文件大小：float cacheSize = [NSFileManager folderSizeAtPath:[UIImage cacheDirectory]];
清空缓存：[[NSFileManager defaultManager] removeItemAtPath:[UIImage cacheDirectory] error:nil];
[[NSURLCache sharedURLCache] removeAllCachedResponses];
